---
title: "Teaching Experience"
toc: TRUE
---

## Independent Instructor

<u>ECON 201: Introduction to Macroeconomics</u>

University of Washington, Winter 2026.

<u>ENGL 299: Intermediate Writing in the Natural Sciences</u>

University of Washington, Spring 2026. Sole instructor of record for a 5-credit writing course in UW's Program for Writing Across Campus, linked to NUTR 200.

## Teaching Assistant

<u>QSCI 381: Introduction to Probability and Statistics</u>

University of Washington, Fall 2024 – Fall 2025. Center for Quantitative Science.

<u>ECON 201: Introduction to Macroeconomics</u>

University of Washington, Spring 2024.

<u>ECON 200: Introduction to Microeconomics</u>

University of Washington, Winter 2024.

## Grader

<u>Reading Comprehension, Critical Thinking, & Writing Skills (RTW) Exam</u>

University of Washington, Department of Economics. Fall 2023 – Present.

<u>ECON 422: Investment, Capital, and Finance</u>

University of Washington, Fall 2025.

<u>ECON 423: Topics in Financial Economics</u>

University of Washington, Spring 2025.

## Prior Teaching

<u>Math Tutor and Learning Assistant</u>

University of Colorado Boulder, Department of Mathematics. January 2022 – August 2023. Provided academic support in calculus and linear algebra, with emphasis on proof techniques and conceptual reasoning.
